import {test} from 'node:test';
import assert from 'node:assert/strict';
import {adminAuthorized,adminWriteAuthorized,validBearer} from '../lib/access-policy.ts';
import {admission,type JobState} from '../lib/job-policy.ts';
const config={ADMIN_EMAILS:'owner@example.test',ADMIN_SYNC_SECRET:'a'.repeat(40),SYNC_CRON_SECRET:'c'.repeat(40)};
test('knowing the endpoint and forging Origin is insufficient',async()=>{assert.equal(await adminWriteAuthorized(new Request('https://site.test/api/admin/sync',{method:'POST',headers:{Origin:'https://site.test'}}),config),false);assert.equal(await adminAuthorized(new Headers(),config),false);});
test('only allowlisted identities can write, with same-origin CSRF protection',async()=>{const h=new Headers({'oai-authenticated-user-id':'site-scoped-id','oai-authenticated-user-email':'owner@example.test'});assert.equal(await adminAuthorized(h,config),true);assert.equal(await adminWriteAuthorized(new Request('https://site.test/api/admin/sync',{headers:h}),config),false);h.set('origin','https://site.test');assert.equal(await adminWriteAuthorized(new Request('https://site.test/api/admin/sync',{headers:h}),config),true);h.set('oai-authenticated-user-email','visitor@example.test');assert.equal(await adminAuthorized(h,config),false);});
test('cron and machine-admin credentials are separate; empty secrets fail closed',async()=>{const h=new Headers({Authorization:`Bearer ${config.SYNC_CRON_SECRET}`});assert.equal(await validBearer(h,config.SYNC_CRON_SECRET),true);assert.equal(await adminAuthorized(h,config),false);assert.equal(await validBearer(h,''),false);h.set('Authorization','Bearer invalid');assert.equal(await validBearer(h,config.SYNC_CRON_SECRET),false);});
test('active jobs, cooldown, continuation and completed-job idempotency',()=>{const job:JobState={id:'a',status:'running',trigger:'admin',startedAt:1000,updatedAt:1000,completedAt:null,lastSuccessfulAt:null,nextStartAt:0,durationMs:0};assert.equal(admission(job,undefined,2000).allowed,false);assert.equal(admission(job,'a',2000).allowed,true);assert.equal(admission(job,'wrong',2000).allowed,false);job.status='completed';job.nextStartAt=10000;assert.equal(admission(job,undefined,2000).allowed,false);assert.equal(admission(job,'a',2000).allowed,false);assert.equal(admission(job,undefined,10001).allowed,true);});
