/* The admin dashboard intentionally polls and refreshes state from an effect. */
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/purity */
'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import {Activity,RefreshCw} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import type {AdminStatus} from '@/lib/jobs';
const date=(value:number|null|undefined)=>value?new Date(value).toISOString().replace('T',' ').slice(0,19)+' UTC':'—';
export default function AdminDashboard(){
 const [data,setData]=useState<AdminStatus|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const load=useCallback(async()=>{try{const r=await fetch('/api/admin/status',{cache:'no-store'});if(!r.ok)throw Error('Administrator status is unavailable.');setData(await r.json() as AdminStatus);}catch(e){setMessage(e instanceof Error?e.message:'Status is unavailable.');}},[]);
 useEffect(()=>{void load();const timer=setInterval(()=>void load(),10000);return()=>clearInterval(timer);},[load]);
 async function sync(){setBusy(true);setMessage('Updating repository signals…');try{let jobId:string|undefined;for(let i=0;i<65;i++){const r=await fetch('/api/admin/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jobId})});const d=await r.json() as {jobId?:string;message:string;done?:boolean;paused?:boolean};setMessage(d.message);await load();if(!r.ok||d.done||d.paused)break;jobId=d.jobId;await new Promise(resolve=>setTimeout(resolve,1500));}}catch{setMessage('Connection interrupted. Saved progress will resume on the next sync.');}finally{setBusy(false);}}
 const summary=data?.sync.summary;
 return <div className="app-shell"><header className="topbar"><Link className="brand" href="/"><Activity/> GitPulse</Link><nav><Link href="/">Explore</Link><span>Administration</span></nav></header><main className="main admin-shell"><div className="headline"><div><h1>Collection status</h1><p>Saved observations stay available while signals update.</p></div><Button className="sync-button" onClick={sync} disabled={busy||!data||data.active}><RefreshCw size={16} className={busy?'spinning':''}/>{busy?'Syncing…':'Sync now'}</Button></div>{message&&<p className="collection-status" role="status">{message}</p>}
 <div className="stats admin-stats">{[['Total repositories',summary?.total],['Current history coverage',data?`${data.coverage} / ${summary?.total}`:undefined],['Score eligible',data?.scoreEligible],['Insufficient history',data?.insufficientHistory],['Failed / pending',summary?`${summary.failed} / ${summary.pending}`:undefined],['Rate limit remaining',data?.sync.rateLimit?.remaining]].map(([label,value])=><div key={String(label)}><span>{label}</span><strong>{value??'—'}</strong></div>)}</div>
 <section className="panel admin-panel"><h2>Latest job</h2><dl className="admin-facts"><dt>Last successful sync</dt><dd>{date(data?.lastSuccessfulAt)}</dd><dt>Last attempted sync</dt><dd>{date(data?.lastAttemptedAt)}</dd><dt>Current status</dt><dd>{data?.status??'Loading…'}</dd><dt>Latest duration</dt><dd>{data?.job?`${(data.job.durationMs/1000).toFixed(1)} seconds`:'—'}</dd><dt>Latest result</dt><dd>{summary?`${summary.metadataSuccess} metadata · ${summary.historySuccess} history · ${summary.rateLimited} rate limited · ${summary.failed} failed`:'—'}</dd><dt>Cooldown until</dt><dd>{data?.job?.nextStartAt&&data.job.nextStartAt>Date.now()?date(data.job.nextStartAt):'None'}</dd><dt>Authentication</dt><dd>{data?.sync.authenticationVerified?'Authenticated and verified':data?.sync.authentication??'—'}</dd></dl></section>
 <section className="panel admin-panel"><h2>Daily updates</h2><p>{data?.schedule.mechanism??'Loading…'}</p><p>Configured daily time: {data?.schedule.timeUTC??'—'} UTC. Next automatic run: not scheduled.</p><p>Connect an external scheduler to the protected POST /api/cron/sync endpoint. No automatic task is currently registered.</p></section>
 <section className="panel admin-panel"><h2>Repositories needing attention</h2><Table><TableHeader><TableRow><TableHead>Repository</TableHead><TableHead>Type</TableHead><TableHead>Details</TableHead></TableRow></TableHeader><TableBody>{data?.sync.missingHistory.map(r=><TableRow key={r.repository}><TableCell>{r.repository}</TableCell><TableCell>{r.status}</TableCell><TableCell>{r.reason} ({r.cachedDays} saved days)</TableCell></TableRow>)}</TableBody></Table>{data&&!data.sync.missingHistory.length&&<p>All tracked repositories have sufficient current history.</p>}</section>
 <details className="panel admin-panel"><summary>Recent API diagnostics</summary><Table><TableHeader><TableRow><TableHead>Time</TableHead><TableHead>Endpoint</TableHead><TableHead>Status / type</TableHead><TableHead>Quota</TableHead><TableHead>Retry / reset</TableHead></TableRow></TableHeader><TableBody>{data?.sync.diagnostics.slice(-30).reverse().map((d,i)=><TableRow key={`${d.at}-${i}`}><TableCell>{date(d.at)}</TableCell><TableCell className="admin-endpoint">{d.endpoint}<br/>{d.authentication}</TableCell><TableCell>{d.status??'No response'} / {d.githubErrorType??'success'}</TableCell><TableCell>{d.remaining??'—'} / {d.limit??'—'}</TableCell><TableCell>{d.retryAfter??'—'} / {date(d.reset?d.reset*1000:null)}</TableCell></TableRow>)}</TableBody></Table></details></main></div>;
}
