import {database,savedRepos,readSyncState} from './storage';
import {collect} from './github';
import {report} from './sync-engine';
import {rank,currentHistory} from './scoring';
import {serverConfig,cooldownMs,scheduleStatus} from './server-config';
import {admission,type JobState} from './job-policy';
export async function readJob():Promise<JobState|null>{const row=await database().prepare('SELECT payload FROM sync_control WHERE name=?').bind('production-job').first<{payload:string}>();return row?JSON.parse(row.payload):null;}
async function writeJob(job:JobState){await database().prepare('INSERT INTO sync_control(name,payload) VALUES (?,?) ON CONFLICT(name) DO UPDATE SET payload=excluded.payload').bind('production-job',JSON.stringify(job)).run();}
export async function adminStatus(){const [job,state,repos,lock]=await Promise.all([readJob(),readSyncState(),savedRepos(),database().prepare('SELECT until FROM job_locks WHERE name=?').bind('production-sync').first<{until:number}>()]);const sync=report(state,repos),ranked=rank(repos),now=Date.now();const legacySuccess=state?.phase==='completed'&&sync.summary.failed===0&&sync.summary.rateLimited===0?state.updatedAt:null;return {job,sync,lastSuccessfulAt:job?.lastSuccessfulAt??legacySuccess,lastAttemptedAt:job?.startedAt??state?.startedAt??null,active:(lock?.until??0)>now,status:(lock?.until??0)>now?'running':job?.status??state?.phase??'idle',coverage:repos.filter(r=>currentHistory(r)).length,scoreEligible:ranked.filter(r=>r.scoringReady).length,insufficientHistory:repos.filter(r=>r.historyAvailable&&r.daily.length<8).length,schedule:scheduleStatus(serverConfig().SYNC_SCHEDULE_UTC)};}
export type AdminStatus=Awaited<ReturnType<typeof adminStatus>>;
export async function executeJob(trigger:'admin'|'cron',requestedId?:string){const db=database(),start=Date.now(),lease=start+300000;const acquired=await db.prepare('INSERT INTO job_locks(name,until) VALUES (?,?) ON CONFLICT(name) DO UPDATE SET until=excluded.until WHERE job_locks.until < ?').bind('production-sync',lease,start).run();if(!acquired.meta.changes)return {status:409,body:{message:'A sync is already in progress.'}};let job:JobState|null=null;try{job=await readJob();const decision=admission(job,requestedId,Date.now());if(!decision.allowed)return {status:decision.status,body:{message:decision.message,retryAt:decision.retryAt,jobId:job?.id,done:decision.status===200}};const gate=await db.prepare('INSERT INTO job_locks(name,until) VALUES (?,?) ON CONFLICT(name) DO UPDATE SET until=excluded.until WHERE job_locks.until < ?').bind('sync-request-window',start+1000,start).run();if(!gate.meta.changes)return {status:429,body:{message:'Please wait before continuing this sync.',retryAt:start+1000,jobId:job?.id}};if(!job||job.status==='completed'){const state=await readSyncState();const successful=state?.phase==='completed'&&Object.values(state.outcomes).every(o=>o.metadata==='success'&&['success','insufficient_history'].includes(o.history));job={id:crypto.randomUUID(),status:'running',trigger,startedAt:start,updatedAt:start,completedAt:null,lastSuccessfulAt:job?.lastSuccessfulAt??(successful?state!.updatedAt:null),nextStartAt:0,durationMs:0};}const previousDuration=job.durationMs;job.status='running';job.updatedAt=Date.now();job.errorType=undefined;await writeJob(job);do{const batch=await collect(serverConfig().GITHUB_TOKEN,job.collectorRunId);job.collectorRunId=batch.runId;job.result=batch.summary;job.updatedAt=Date.now();job.durationMs=previousDuration+Date.now()-start;if(batch.paused){job.status='paused';job.nextStartAt=batch.nextSyncAt??Date.now()+60000;}if(batch.done){job.status='completed';job.completedAt=Date.now();job.nextStartAt=Date.now()+cooldownMs(serverConfig().SYNC_COOLDOWN_SECONDS);if(batch.summary.failed===0&&batch.summary.rateLimited===0&&batch.summary.pending===0)job.lastSuccessfulAt=job.completedAt;}await writeJob(job);if(batch.done||batch.paused)break;}while(Date.now()-start<40000);return {status:job.status==='running'?202:200,body:{jobId:job.id,done:job.status==='completed',paused:job.status==='paused',retryAt:job.nextStartAt||null,summary:job.result,message:job.status==='completed'?'Sync completed.':job.status==='paused'?'Sync paused; saved progress will resume after the cooldown.':'Sync is in progress.'}};}catch{if(job){job.status='failed';job.errorType='unknown_error';job.updatedAt=Date.now();job.nextStartAt=Date.now()+60000;await writeJob(job);}return {status:503,body:{message:'Sync was interrupted. Saved observations and progress are preserved.',jobId:job?.id,retryAt:job?.nextStartAt}};}finally{await db.prepare('UPDATE job_locks SET until=0 WHERE name=? AND until=?').bind('production-sync',lease).run();}}
